config/routes.rb
Found::Application.routes.draw do
  devise_for :users
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  resources :renters

  resources :landlords

  get '/renteeform' => 'landlords#new'
  get '/renterform' => 'renters#new'
  get '/thanks' => 'static_pages#thanks'
  get 'auth' => 'static_pages#auth'

  root :to => 'static_pages#index'

end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
  attr_accessible :amenities, :desk_seats, :email, :hours_avail_am, :hours_avail_pm, :internet, :name, :neighborhood, :phone, :price, :total_seats, :avail_on_weekends
end
# == Schema Information
#
# Table name: landlords
#
#  id                :integer         not null, primary key
#  name              :string(255)
#  email             :string(255)
#  phone             :string(255)
#  neighborhood      :string(255)
#  hours_avail_am    :integer
#  hours_avail_pm    :integer
#  internet          :string(255)
#  desk_seats        :integer
#  total_seats       :integer
#  price             :integer
#  amenities         :string(255)
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#  avail_on_weekends :string(255)
#

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  attr_accessible :name

  default_scope order('name ASC')
end
# == Schema Information
#
# Table name: neighborhoods
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

app/models/renter.rb
class Renter < ActiveRecord::Base
  attr_accessible :acceptable_desks, :acceptable_seats, :hours_required_am, :hours_required_pm, :min_desks, :min_seats, :price, :team_size, :name, :email, :phone
end
# == Schema Information
#
# Table name: renters
#
#  id                :integer         not null, primary key
#  team_size         :integer
#  min_desks         :integer
#  acceptable_desks  :integer
#  min_seats         :integer
#  acceptable_seats  :integer
#  price             :integer
#  hours_required_am :integer
#  hours_required_pm :integer
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#  name              :string(255)
#  email             :string(255)
#  phone             :string(255)
#

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  before_filter :authenticate_user!, only: [:show, :index, :edit, :update, :destroy]
  # GET /landlords
  # GET /landlords.json
  def index
    @landlords = Landlord.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @landlords }
    end
  end

  # GET /landlords/1
  # GET /landlords/1.json
  def show
    @landlord = Landlord.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @landlord }
    end
  end

  # GET /landlords/new
  # GET /landlords/new.json
  def new
    @landlord = Landlord.new
    @neighborhoods = Neighborhood.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @landlord }
    end
  end

  # GET /landlords/1/edit
  def edit
    @landlord = Landlord.find(params[:id])
  end

  # POST /landlords
  # POST /landlords.json
  def create
    @landlord = Landlord.new(params[:landlord])

    respond_to do |format|
      if @landlord.save
        UserMailer.landlord_confirmation(@landlord).deliver
        format.html { redirect_to '/thanks', notice: 'Landlord was successfully created.' }
        format.json { render json: @landlord, status: :created, location: @landlord }
      else
        format.html { render action: "new" }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /landlords/1
  # PUT /landlords/1.json
  def update
    @landlord = Landlord.find(params[:id])

    respond_to do |format|
      if @landlord.update_attributes(params[:landlord])
        format.html { redirect_to @landlord, notice: 'Landlord was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1
  # DELETE /landlords/1.json
  def destroy
    @landlord = Landlord.find(params[:id])
    @landlord.destroy

    respond_to do |format|
      format.html { redirect_to landlords_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/renters_controller.rb
class RentersController < ApplicationController
  before_filter :authenticate_user!, only: [:show, :index, :edit, :update, :destroy]

  # GET /renters
  # GET /renters.json
  def index
    @renters = Renter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @renters }
    end
  end

  # GET /renters/1
  # GET /renters/1.json
  def show
    @renter = Renter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @renter }
    end
  end

  # GET /renters/new
  # GET /renters/new.json
  def new
    @renter = Renter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @renter }
    end
  end

  # GET /renters/1/edit
  def edit
    @renter = Renter.find(params[:id])
  end

  # POST /renters
  # POST /renters.json
  def create
    @renter = Renter.new(params[:renter])

    respond_to do |format|
      if @renter.save
        UserMailer.renter_confirmation(@renter).deliver
        format.html { redirect_to "/thanks", notice: 'Renter was successfully created.' }
        format.json { render json: @renter, status: :created, location: @renter }
      else
        format.html { render action: "new" }
        format.json { render json: @renter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /renters/1
  # PUT /renters/1.json
  def update
    @renter = Renter.find(params[:id])

    respond_to do |format|
      if @renter.update_attributes(params[:renter])
        format.html { redirect_to @renter, notice: 'Renter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @renter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /renters/1
  # DELETE /renters/1.json
  def destroy
    @renter = Renter.find(params[:id])
    @renter.destroy

    respond_to do |format|
      format.html { redirect_to renters_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :authenticate_user!, only: [:auth]

  def index
  end

  def thanks
  	
  end

  def auth   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/helpers/renters_helper.rb
module RentersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/landlords/_form.html.erb
<%= form_for @landlord, :html => {:id => "signup-form", :class => "form-horizontal"} do |f| %>
  <% if @landlord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@landlord.errors.count, "error") %> prohibited this landlord from being saved:</h2>

      <ul>
      <% @landlord.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :class => "input-xlarge", :placeholder => "Name"%>
  </div>
  <div class="field">
    <%= f.text_field :email, :class => "input-xlarge", :placeholder => "Email" %>
  </div>
  <div class="field">
    <%= f.telephone_field :phone, :class => "input-xlarge", :placeholder => "Phone Number (Optional)" %><br><br>
  </div>
  <div class="field">
    <%= f.label :neighborhood %>
    <%= f.select :neighborhood, options_from_collection_for_select(@neighborhoods, 'name', 'name'), {:class=>"input-xlarge"} %><br><br>
  </div>
  <div class="field">
    <%= f.label :availability, "Availability (Mon - Fri)" %>
    <select name="landlord[hours_avail_am]" class="input-xlarge">
      <option value=0>From</option>
      <option value=6>6am</option>
      <option value=7>7am</option>
      <option value=8>8am</option>
      <option value=9>9am</option>
      <option value=10>10am</option>
      <option value=11>11am</option>
      <option value=12>12pm</option>
    </select><br><br>
  <div class="field">
    <select name="landlord[hours_avail_pm]" class="input-xlarge">
      <option value=0>Until</option>
      <option value=5>5pm</option>
      <option value=6>6pm</option>
      <option value=7>7pm</option>
      <option value=8>8pm</option>
      <option value=9>9pm</option>
      <option value=10>10pm</option>
      <option value=11>11pm</option>
      <option value=12>Midnight</option>
    </select><br><br>
  </div>
    <%= f.label :avail_on_weekends, "Available on Weekends?" %>
  <div class="field">
    <%= f.check_box :avail_on_weekends %>
  </div><br>

  <div class="field">
    <%= f.label :internet, "Internet Speed" %>
    <select name="landlord[internet]" class="input-xlarge">
      <option value="Slow">Slow</option>
      <option value="Medium">Medium</option>
      <option value="Fast">Fast</option>
      <option value="Super Speed">Super Speed</option>
      <option value="No Internet">No Internet</option>
    </select><br><br><br>
  </div>
  <div class="field">
    <label>Available Desks: <span id="avail_desks_output">0</span></label><br/>
    <%= f.range_field :desk_seats, :in => 0..10, :step => '1', :id => "avail_desks", :value => 0 %>
  </div><br><br>
  <div class="field">
    <label>Available Seats: <span id="avail_seats_output">0</span></label><br/>
    <%= f.range_field :total_seats, :in => 0..15, :step => '1', :id => "avail_seats", :value => 0 %>
  </div><br><br>
  <div class="field">
    <label>Desired Monthly Income: $<span id="price_output">0</span></label><br/>
    <%= f.range_field :price, :in => 0..5000, :step => '250', :id => "price", :value => 0 %>
  </div><br><br>
<!--   <div class="field">
    <%= f.label :amenities %><br />
    <%= f.text_field :amenities %>
  </div> -->
  <div class="actions">
    <%= f.submit "Submit Form", :class => "btn-main" %>
  </div>
<% end %>

<script type="text/javascript">
  function CurrencyFormatted(amount)
    {
        var i = parseFloat(amount);
        if(isNaN(i)) { i = 0; }
        var minus = '';
        if(i < 0) { minus = '-'; }
        i = Math.abs(i);
        i = parseInt((i + .005) * 100);
        i = i / 100;
        s = new String(i);
        if(s.indexOf('.') < 0) { s; }
        if(s.indexOf('.') == (s.length - 2)) { s += '0'; }
        s = minus + s;
        return s;
    }

  $.fn.digits = function(){ 
    return this.each(function(){ 
        $(this).text( $(this).text().replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,") ); 
    })
  }

  $("#avail_desks").change(function () {                    
     var newValue = $('#avail_desks').val();
     $("#avail_desks_output").html(newValue);
  });
  $("#avail_seats").change(function () {                    
     var newValue = $('#avail_seats').val();
     $("#avail_seats_output").html(newValue);
  });
  $("#price").change(function () {                    
     var newValue = $('#price').val();
     var newPrice = CurrencyFormatted(parseInt(newValue));
     $("#price_output").html(newPrice).digits();
  });
</script>

app/views/landlords/edit.html.erb
<h1>Editing landlord</h1>

<%= render 'form' %>

<%= link_to 'Show', @landlord %> |
<%= link_to 'Back', landlords_path %>

app/views/landlords/index.html.erb
<h1>Listing landlords</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Neighborhood</th>
    <th>From (am)</th>
    <th>Until (pm)</th>
    <th>Weekends?</th>
    <th>Internet</th>
    <th>Desk seats</th>
    <th>Total seats</th>
    <th>Price</th>
    <th>Amenities</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @landlords.each do |landlord| %>
  <tr>
    <td><%= landlord.name %></td>
    <td><%= landlord.email %></td>
    <td><%= landlord.phone %></td>
    <td><%= landlord.neighborhood %></td>
    <td><%= landlord.hours_avail_am %></td>
    <td><%= landlord.hours_avail_pm %></td>
    <td><%= landlord.avail_on_weekends %></td>
    <td><%= landlord.internet %></td>
    <td><%= landlord.desk_seats %></td>
    <td><%= landlord.total_seats %></td>
    <td><%= landlord.price %></td>
    <td><%= landlord.amenities %></td>
    <td><%= link_to 'Show', landlord %></td>
    <td><%= link_to 'Edit', edit_landlord_path(landlord) %></td>
    <td><%= link_to 'Destroy', landlord, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Landlord', new_landlord_path %>

app/views/landlords/new.html.erb
<%= render 'shared/header' %>

<!--Content-->

<section id="signup">
  <div class="container">
    <div class="row margin-40">
      
      <div class="span6 offset3 text-center signup">
          <h3>Have Available Space?</h3><br/>
          <div class="form-subtext">Fill out the form below to get matched<br class="desktop">with a top startup team looking to rent office space<br></div>

        	<%= render 'form' %>
  	  
      </div><!--End Span6-->
      
    </div><!--End Row-->
  </div><!--End Container-->
</section>

<%= render 'shared/footer' %>

app/views/landlords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @landlord.name %>
</p>

<p>
  <b>Email:</b>
  <%= @landlord.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @landlord.phone %>
</p>

<p>
  <b>Neighborhood:</b>
  <%= @landlord.neighborhood %>
</p>

<p>
  <b>Hours avail am:</b>
  <%= @landlord.hours_avail_am %>
</p>

<p>
  <b>Hours avail pm:</b>
  <%= @landlord.hours_avail_pm %>
</p>

<p>
  <b>Weekends?:</b>
  <%= @landlord.avail_on_weekends %>
</p>

<p>
  <b>Internet:</b>
  <%= @landlord.internet %>
</p>

<p>
  <b>Desk seats:</b>
  <%= @landlord.desk_seats %>
</p>

<p>
  <b>Total seats:</b>
  <%= @landlord.total_seats %>
</p>

<p>
  <b>Price:</b>
  <%= @landlord.price %>
</p>

<p>
  <b>Amenities:</b>
  <%= @landlord.amenities %>
</p>


<%= link_to 'Edit', edit_landlord_path(@landlord) %> |
<%= link_to 'Back', landlords_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Found</title>
  <meta charset="utf-8">
  <meta name="keywords" content="made with bootstrap, wrap bootstrap themes, bootstrap agency themes, creative bootstrap sites, Lava theme, responsive bootstrap theme, mobile website themes, bootstrap portfolio, theme armada">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">
  <meta property="og:title" content="Lava | Designed By Theme Armada">
	<meta property="og:type" content="website">
	<meta property="og:url" content="http://www.themearmada.com/demos/lava">
	<meta property="og:site_name" content="Theme Armada">
	<meta property="og:description" content="made with bootstrap, wrap bootstrap themes, bootstrap agency themes, creative bootstrap sites, Lava theme, responsive bootstrap theme, mobile website themes, bootstrap portfolio, theme armada">
<!--   <FilesMatch ".(ttf|otf|woff)$">
  Header set Access-Control-Allow-Origin "*"
  </FilesMatch> -->
  <script type="text/javascript">
  // location ~* .(eot|ttf|woff)$ { 
  // add_header Access-Control-Allow-Origin *; 
  // }</script>

  <!-- Styles -->

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
	<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
	<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/renters/_form.html.erb
<%= form_for @renter, :html => {:id => "signup-form", :class => "form-horizontal"} do |f| %>
  <% if @renter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@renter.errors.count, "error") %> prohibited this renter from being saved:</h2>

      <ul>
      <% @renter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :name, :class => "input-xlarge", :placeholder => "Name"%>
  </div>
  <div class="field">
    <%= f.text_field :email, :class => "input-xlarge", :placeholder => "Email" %>
  </div>
  <div class="field">
    <%= f.telephone_field :phone, :class => "input-xlarge", :placeholder => "Phone Number (Optional)" %><br><br>
  </div>


  <div class="field">
    <label>Team Size: <span id="team_size_output">0</span></label><br/>
    <%= f.range_field :team_size, :in => 0..10, :step => '1', :id => "team_size", :value => 0 %>
  </div><br><br>

  <div class="field">
    <%= f.label :desired_time, "Desired Hours (Mon - Fri)" %>
    <select name="renter[hours_required_am]" class="input-xlarge">
      <option value=0>From</option>
      <option value=6>6am</option>
      <option value=7>7am</option>
      <option value=8>8am</option>
      <option value=9>9am</option>
      <option value=10>10am</option>
      <option value=11>11am</option>
      <option value=12>12pm</option>
    </select><br><br>
  <div class="field">
    <select name="renter[hours_required_pm]" class="input-xlarge">
      <option value=0>Until</option>
      <option value=5>5pm</option>
      <option value=6>6pm</option>
      <option value=7>7pm</option>
      <option value=8>8pm</option>
      <option value=9>9pm</option>
      <option value=10>10pm</option>
      <option value=11>11pm</option>
      <option value=12>Midnight</option>
    </select><br><br>
  </div>

  <div class="field">
    <label>Min # of Desks: <span id="min_desks_output">0</span></label><br/>
    <%= f.range_field :min_desks, :in => 0..10, :step => '1', :id => "min_desks", :value => 0 %>
  </div><br><br>
  <div class="field">
    <label>Ideal # of Desks: <span id="acceptable_desks_output">0</span></label><br/>
    <%= f.range_field :acceptable_desks, :in => 0..10, :step => '1', :id => "acceptable_desks", :value => 0 %>
  </div><br><br>
  <div class="field">
    <label>Min # of Seats: <span id="min_seats_output">0</span></label><br/>
    <%= f.range_field :min_seats, :in => 0..10, :step => '1', :id => "min_seats", :value => 0 %>
  </div><br><br>
  <div class="field">
    <label>Ideal # of Seats: <span id="acceptable_seats_output">0</span></label><br/>
    <%= f.range_field :acceptable_seats, :in => 0..10, :step => '1', :id => "acceptable_seats", :value => 0 %>
  </div><br><br>
  <div class="field">
    <label>Max Monthly Rent: $<span id="price_output">0</span></label><br/>
    <%= f.range_field :price, :in => 0..5000, :step => '250', :id => "price", :value => 0 %>
  </div><br><br>
  <div class="actions">
    <%= f.submit "Submit Form", :class => "btn-main" %>
  </div>
<% end %>

<script type="text/javascript">
  function CurrencyFormatted(amount)
    {
        var i = parseFloat(amount);
        if(isNaN(i)) { i = 0; }
        var minus = '';
        if(i < 0) { minus = '-'; }
        i = Math.abs(i);
        i = parseInt((i + .005) * 100);
        i = i / 100;
        s = new String(i);
        if(s.indexOf('.') < 0) { s; }
        if(s.indexOf('.') == (s.length - 2)) { s += '0'; }
        s = minus + s;
        return s;
    }

  $.fn.digits = function(){ 
    return this.each(function(){ 
        $(this).text( $(this).text().replace(/(\d)(?=(\d\d\d)+(?!\d))/g, "$1,") ); 
    })
  }

  $("#team_size").change(function () {                    
     var newValue = $('#team_size').val();
     $("#team_size_output").html(newValue);
  });
  $("#min_desks").change(function () {                    
     var newValue = $('#min_desks').val();
     $("#min_desks_output").html(newValue);
  });
  $("#acceptable_desks").change(function () {                    
     var newValue = $('#acceptable_desks').val();
     $("#acceptable_desks_output").html(newValue);
  });
  $("#min_seats").change(function () {                    
     var newValue = $('#min_seats').val();
     $("#min_seats_output").html(newValue);
  });
  $("#acceptable_seats").change(function () {                    
     var newValue = $('#acceptable_seats').val();
     $("#acceptable_seats_output").html(newValue);
  });
  $("#price").change(function () {                    
     var newValue = $('#price').val();
     var newPrice = CurrencyFormatted(parseInt(newValue));
     $("#price_output").html(newPrice).digits();
  });
</script>

app/views/renters/edit.html.erb
<h1>Editing renter</h1>

<%= render 'form' %>

<%= link_to 'Show', @renter %> |
<%= link_to 'Back', renters_path %>

app/views/renters/index.html.erb
<h1>Listing renters</h1>

<table>
  <tr>
    <th>Team size</th>
    <th>Min desks</th>
    <th>Acceptable desks</th>
    <th>Min seats</th>
    <th>Acceptable seats</th>
    <th>Price</th>
    <th>Hours required am</th>
    <th>Hours required pm</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @renters.each do |renter| %>
  <tr>
    <td><%= renter.team_size %></td>
    <td><%= renter.min_desks %></td>
    <td><%= renter.acceptable_desks %></td>
    <td><%= renter.min_seats %></td>
    <td><%= renter.acceptable_seats %></td>
    <td><%= renter.price %></td>
    <td><%= renter.hours_required_am %></td>
    <td><%= renter.hours_required_pm %></td>
    <td><%= link_to 'Show', renter %></td>
    <td><%= link_to 'Edit', edit_renter_path(renter) %></td>
    <td><%= link_to 'Destroy', renter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Renter', new_renter_path %>

app/views/renters/new.html.erb
<%= render 'shared/header' %>

<!--Content-->

<section id="signup">
  <div class="container">
    <div class="row margin-40">
      
      <div class="span6 offset3 text-center signup">
          <h3>Need Office Space?</h3><br/>
          <div class="form-subtext">Fill out the form below to find comfortable, <br class="desktop">affordable, and short-term office space<br></div>

        	<%= render 'form' %>
  	  
      </div><!--End Span6-->
      
    </div><!--End Row-->
  </div><!--End Container-->
</section>

<%= render 'shared/footer' %>

app/views/renters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Team size:</b>
  <%= @renter.team_size %>
</p>

<p>
  <b>Min desks:</b>
  <%= @renter.min_desks %>
</p>

<p>
  <b>Acceptable desks:</b>
  <%= @renter.acceptable_desks %>
</p>

<p>
  <b>Min seats:</b>
  <%= @renter.min_seats %>
</p>

<p>
  <b>Acceptable seats:</b>
  <%= @renter.acceptable_seats %>
</p>

<p>
  <b>Price:</b>
  <%= @renter.price %>
</p>

<p>
  <b>Hours required am:</b>
  <%= @renter.hours_required_am %>
</p>

<p>
  <b>Hours required pm:</b>
  <%= @renter.hours_required_pm %>
</p>


<%= link_to 'Edit', edit_renter_path(@renter) %> |
<%= link_to 'Back', renters_path %>

app/views/shared/_footer.html.erb
    <!--Bottom Section-->
    <section id="bottom">
      <div class="container">
        <div class="row">
          <div class="span10 offset1 text-center">
            <p>917.727.7245  |  <a href="mailto:hello@found.io"><i class="icon-envelope-alt"></i> hello@found.io</a></p>
            <hr>
          </div>
        </div>
        
        <div class="row">
          <div class="span10 offset1 text-center">
            <!--Social Icons-->          
            <ul class="social-icons">
              <li><a class="twitter" href="http://www.twitter.com/found_io" target="_blank"><i class="icon-twitter icon-3x"></i></a></li>
              <li><a class="facebook" href="http://www.facebook.com" target="_blank"><i class="icon-facebook icon-3x"></i></a></li>
<!--              <li><a class="google" href="mailto:hello@found.io.com?subject=Hello" target="_blank"><i class="icon-envelope icon-3x"></i></a></li> -->
            </ul>
          </div>
        </div>
        
      </div>
    </section>
    
    
    <section id="footer">
      <div class="container">
        <div class="row">
          <div class="span12 text-center">
            <p>© 2013 Innerspace, LLC</a></p>
          </div>
        </div>
      </div>
    </section>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to('/') do %>
        <%= image_tag("found_logo.png", :class => "brand", :alt => "logo", :width => "160") %>
      <% end %>
      <div class="nav-collapse collapse">
        <ul class="nav pull-right">
        	<li><%= link_to "Home", "/"  %></li>
        	<!-- <li><%= link_to "Connect", "/#connect"  %></li> -->
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/static_pages/auth.html.erb
<style type="text/css">
  a:visited, a:hover {
    color: black;
  }
</style>
<div class="container">
  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Logout", destroy_user_session_path, method: :delete %><br><br>
      <%= link_to "Renter Signups", renters_path, :class => "btn-main btn-landlord", :style => "color:white; padding-right: 20px;" %>
      <%= link_to "Office Signups", landlords_path, :class => "btn-main btn-renter", :style => "color:white; padding-right: 20px;" %>

    <% else %>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
</div>

app/views/static_pages/thanks.html.erb
<%= render 'shared/header' %>

<!--Content-->
<section id="content1">
  <div class="container">
    <div class="row margin-40">
      <div class="span12 thank-you-div">
        <p class="lead thank-you thank-you-top">Thanks for signing up!</p>
        <p class="lead thank-you thank-you-bottom">We'll get back to you as <br class="mobile">soon as we have a match.</p>
      </div>
    </div>   
  </div>
</section>



<%= render 'shared/footer' %>